INSERT INTO meta_criteria VALUES(34, 'MEDICATIONS:ANTIPSYCHOTIC', 'List of Medications for treating Psychotic Disorders');

INSERT INTO meta_conditions VALUES(34, 'ALL', 'NONE', '%abilify%', 'Antipsychotic  medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(34, 'ALL', 'NONE', '%amitriptyline%', 'Antipsychotic  medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(34, 'ALL', 'NONE', '%aripiprazole%', 'Antipsychotic  medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(34, 'ALL', 'NONE', '%asenapine%', 'Antipsychotic  medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(34, 'ALL', 'NONE', '%cariprazine%', 'Antipsychotic  medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(34, 'ALL', 'NONE', '%chlorpromazine%', 'Antipsychotic  medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(34, 'ALL', 'NONE', '%clozapine%', 'Antipsychotic  medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(34, 'ALL', 'NONE', '%clozaril%', 'Antipsychotic  medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(34, 'ALL', 'NONE', '%compazine %', 'Antipsychotic  medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(34, 'ALL', 'NONE', '%compro %', 'Antipsychotic  medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(34, 'ALL', 'NONE', '%etrafon,%', 'Antipsychotic  medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(34, 'ALL', 'NONE', '%fanapt%', 'Antipsychotic  medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(34, 'ALL', 'NONE', '%fluphenazine%', 'Antipsychotic  medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(34, 'ALL', 'NONE', '%geodon%', 'Antipsychotic  medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(34, 'ALL', 'NONE', '%haldol%', 'Antipsychotic  medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(34, 'ALL', 'NONE', '%haloperidol%', 'Antipsychotic  medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(34, 'ALL', 'NONE', '%iloperidone%', 'Antipsychotic  medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(34, 'ALL', 'NONE', '%invega%', 'Antipsychotic  medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(34, 'ALL', 'NONE', '%latuda%', 'Antipsychotic  medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(34, 'ALL', 'NONE', '%loxapine%', 'Antipsychotic  medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(34, 'ALL', 'NONE', '%loxitane%', 'Antipsychotic  medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(34, 'ALL', 'NONE', '%lurasidone%', 'Antipsychotic  medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(34, 'ALL', 'NONE', '%mellaril%', 'Antipsychotic  medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(34, 'ALL', 'NONE', '%moban%', 'Antipsychotic  medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(34, 'ALL', 'NONE', '%molindone%', 'Antipsychotic  medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(34, 'ALL', 'NONE', '%navane%', 'Antipsychotic  medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(34, 'ALL', 'NONE', '%olanzapine%', 'Antipsychotic  medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(34, 'ALL', 'NONE', '%orap%', 'Antipsychotic  medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(34, 'ALL', 'NONE', '%oxilapine%', 'Antipsychotic  medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(34, 'ALL', 'NONE', '%paliperidone%', 'Antipsychotic  medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(34, 'ALL', 'NONE', '%permitil%', 'Antipsychotic  medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(34, 'ALL', 'NONE', '%perphenazine%', 'Antipsychotic  medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(34, 'ALL', 'NONE', '%pimozide%', 'Antipsychotic  medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(34, 'ALL', 'NONE', '%prochlorperazine%', 'Antipsychotic  medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(34, 'ALL', 'NONE', '%procomp%', 'Antipsychotic  medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(34, 'ALL', 'NONE', '%prolixin%', 'Antipsychotic  medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(34, 'ALL', 'NONE', '%promapar%', 'Antipsychotic  medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(34, 'ALL', 'NONE', '%quetiapine%', 'Antipsychotic  medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(34, 'ALL', 'NONE', '%risperdal%', 'Antipsychotic  medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(34, 'ALL', 'NONE', '%risperidone%', 'Antipsychotic  medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(34, 'ALL', 'NONE', '%saphris%', 'Antipsychotic  medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(34, 'ALL', 'NONE', '%seroquel %', 'Antipsychotic  medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(34, 'ALL', 'NONE', '%seroquel%', 'Antipsychotic  medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(34, 'ALL', 'NONE', '%stelazine%', 'Antipsychotic  medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(34, 'ALL', 'NONE', '%sycrest%', 'Antipsychotic  medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(34, 'ALL', 'NONE', '%symbyax%', 'Antipsychotic  medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(34, 'ALL', 'NONE', '%thioridazine%', 'Antipsychotic  medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(34, 'ALL', 'NONE', '%thiothixene%', 'Antipsychotic  medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(34, 'ALL', 'NONE', '%thorazine%', 'Antipsychotic  medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(34, 'ALL', 'NONE', '%triavil%', 'Antipsychotic  medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(34, 'ALL', 'NONE', '%trifluoperazine%', 'Antipsychotic  medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(34, 'ALL', 'NONE', '%trilafon%', 'Antipsychotic  medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(34, 'ALL', 'NONE', '%vraylar%', 'Antipsychotic  medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(34, 'ALL', 'NONE', '%ziprasidone%', 'Antipsychotic  medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(34, 'ALL', 'NONE', '%zyprexa%', 'Antipsychotic  medication', 'MED', 'LIKE', 'I');

COMMIT;