DROP TABLE dsrip_report_tr001_epic PURGE;

CREATE TABLE dsrip_report_tr001_epic
(
  report_period_start_dt    DATE,
  MRN_EMPI                  VARCHAR2(100 CHAR),
  PATIENT_NAME              VARCHAR2(255 CHAR),
  PATIENT_DOB               VARCHAR2(255 CHAR),
  MRN                       VARCHAR2(102 CHAR),
  VISIT_ID                  NUMBER(18) NOT NULL,
  PRIM_CARE_PROVIDER        VARCHAR2(200 CHAR),
  HOSPITALIZATION_FACILITY  VARCHAR2(80 CHAR),
  ADMISSION_DT              TIMESTAMP(6),
  DISCHARGE_DT              TIMESTAMP(6),
  FOLLOW_UP_VISIT_ID        NUMBER(18),
  FOLLOW_UP_DT              VARCHAR2(255 CHAR),
  FOLLOW_UP_FACILITY        VARCHAR2(80 CHAR),
  FOLLOWUP_DEPARTMENT       VARCHAR2(254 CHAR),
  FOLLOWUPPROVNAME          VARCHAR2(200 CHAR),
  FOLLOWUPPROVTYPE          VARCHAR2(66 CHAR),
  FOLLOWUPPROVSPECIALITY    VARCHAR2(254 CHAR),
  PAYOR1                    VARCHAR2(254 CHAR),
  PAYOR2                    VARCHAR2(254 CHAR),
  PAYOR3                    VARCHAR2(254 CHAR),
  SEVENDAY_FOLLOWUP         VARCHAR2(255 CHAR),
  THIRTYDAY_FOLLOWUP        VARCHAR2(255 CHAR),
  PAYORPATID                VARCHAR2(18 CHAR),
  PAT_ID                    VARCHAR2(18 CHAR),
  SOURCE                    VARCHAR2(4 CHAR),
  EPIC_FLAG                 CHAR(1 CHAR),
  ETL_LOAD_DATE             TIMESTAMP(6),
  CONSTRAINT PK_EPIC_BH_FOLLOW_UP_VISITS PRIMARY KEY(visit_id)
) COMPRESS BASIC;
