DROP TABLE dsrip_report_tr001_epic PURGE;

CREATE TABLE dsrip_report_tr001_epic
(
  report_period_start_dt    DATE,
  mrn_empi                  VARCHAR2(100 CHAR),
  patient_name              VARCHAR2(255 CHAR),
  patient_dob               VARCHAR2(255 CHAR),
  add_line_1                VARCHAR2(255),
  add_line_2                VARCHAR2(255),
  city                      VARCHAR2(255),
  zip                       VARCHAR2(20),
  state                     VARCHAR2(80),
  pat_home_phone            VARCHAR2(50),
  pat_work_phone            VARCHAR2(50),
  mrn                       VARCHAR2(102 CHAR),
  visit_id                  NUMBER(18) NOT NULL,
  prim_care_provider        VARCHAR2(200 CHAR),
  hospitalization_facility  VARCHAR2(80 CHAR),
  admission_dt              TIMESTAMP(6),
  discharge_dt              TIMESTAMP(6),
  follow_up_visit_id        NUMBER(18),
  follow_up_dt              VARCHAR2(255 CHAR),
  follow_up_facility        VARCHAR2(80 CHAR),
  followup_department       VARCHAR2(254 CHAR),
  FollowUpProvName          VARCHAR2(200 CHAR),
  FollowUpProvType          VARCHAR2(66 CHAR),
  FollowUpProvSpeciality    VARCHAR2(254 CHAR),
  payor1                    VARCHAR2(254 CHAR),
  payor2                    VARCHAR2(254 CHAR),
  payor3                    VARCHAR2(254 CHAR),
  SevenDay_FollowUp         VARCHAR2(255 CHAR),
  ThirtyDay_FollowUp        VARCHAR2(255 CHAR),
  source                    VARCHAR2(4 CHAR),
  epic_flag                 CHAR(1 CHAR),
  etl_load_date             TIMESTAMP(6),
  CONSTRAINT pk_epic_bh_follow_up_visits PRIMARY KEY(visit_id)
) COMPRESS BASIC;
