CREATE TABLESPACE hadoop;

CREATE USER hadoop_ambari IDENTIFIED BY m DEFAULT TABLESPACE hadoop TEMPORARY TABLESPACE temp;
GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE, SELECT_CATALOG_ROLE, CREATE SESSION, CREATE TABLE, CREATE SEQUENCE TO hadoop_ambari;

CREATE USER hadoop_hive IDENTIFIED BY m DEFAULT TABLESPACE hadoop TEMPORARY TABLESPACE temp;
GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE, SELECT_CATALOG_ROLE, CREATE SESSION, CREATE TABLE, CREATE SEQUENCE TO hadoop_hive;

CREATE USER hadoop_oozie IDENTIFIED BY m DEFAULT TABLESPACE hadoop TEMPORARY TABLESPACE temp;
GRANT ALL PRIVILEGES TO hadoop_oozie;
GRANT CONNECT, RESOURCE, SELECT_CATALOG_ROLE, UNLIMITED TABLESPACE TO hadoop_oozie;

CREATE USER hadoop_ranger IDENTIFIED BY m DEFAULT TABLESPACE hadoop TEMPORARY TABLESPACE temp;
GRANT CONNECT, RESOURCE, SELECT_CATALOG_ROLE, UNLIMITED TABLESPACE TO hadoop_ranger;
