DROP TABLE DSRIP_TR016_PAYERS PURGE;

CREATE TABLE DSRIP_TR016_PAYERS
(
  NETWORK     VARCHAR2(3),
  VISIT_ID    NUMBER(12)                        NOT NULL,
  PAYER_ID    NUMBER(12),
  PAYER_RANK  NUMBER, 
  CONSTRAINT PK_TR016_PAYERS PRIMARY KEY(NETWORK, VISIT_ID, PAYER_ID)
) ORGANIZATION INDEX;
