ALTER DATABASE ARCHIVELOG;

ALTER SYSTEM CHECKPOINT;
ALTER SYSTEM ARCHIVE LOG CURRENT;

SELECT * FROM v$archived_log;

CREATE RESTORE POINT rp_080205165800 GUARANTEE FLASHBACK DATABASE;

WITH rpv AS
(
  SELECT name, time
  FROM v$restore_point
  WHERE guarantee_flashback_database='YES'
)
SELECT name FROM rpv WHERE time = (SELECT MAX(time) FROM rpv));

FLASHBACK DATABASE TO RESTORE POINT rp_080205132400;

