exec dbm.drop_tables('CNF_DW_REFRESH');

CREATE TABLE cnf_dw_refresh
(
  etl_step_num      NUMBER(10) CONSTRAINT pk_cnf_dw_refresh PRIMARY KEY,
  operation         VARCHAR2(100 BYTE) NOT NULL,       
  target_table      VARCHAR2(30 BYTE) NOT NULL,
  target_partition  VARCHAR2(256 BYTE),
  data_source       VARCHAR2(512 BYTE) NOT NULL,
  uk_col_list       VARCHAR2(256 BYTE),
  where_clause      VARCHAR2(2000 BYTE),
  delete_condition  VARCHAR2(2000 BYTE),
  error_table       VARCHAR2(30 BYTE)
);

GRANT SELECT ON cnf_dw_refresh TO PUBLIC;

truncate table cnf_dw_refresh;

INSERT INTO cnf_dw_refresh VALUES(10, 'MERGE', 'REF_ORDER_TYPES', NULL, 'SELECT DISTINCT order_type_id, name FROM order_type', NULL, NULL, NULL, NULL);
INSERT INTO cnf_dw_refresh VALUES(20, 'MERGE', 'REF_PROC_EVENT_ARCHIVE_TYPES', NULL, 'SELECT DISTINCT archive_type_id, name FROM proc_event_archive_type', NULL, 'WHERE archive_type_id <> 0', NULL, NULL);
INSERT INTO cnf_dw_refresh VALUES(50, 'MERGE', 'DIM_PAYERS', NULL, 'PT008.PAYER_MAPPING', 'NETWORK,PAYER_ID', NULL, NULL, NULL);
INSERT INTO cnf_dw_refresh VALUES(90, 'MERGE /*+ PARALLEL(16)*/', 'REF_DIAGNOSES', NULL, 'V_REF_DIAGNOSES', NULL, NULL, 'DELETE_FLAG=''Y''', NULL);
INSERT INTO cnf_dw_refresh VALUES(95, 'EQUALIZE /*+ PARALLEL(16)*/', 'MAP_DIAGNOSES_CODES', NULL, 'V_MAP_DIAGNOSES_CODES', NULL, NULL, NULL, NULL);
INSERT INTO cnf_dw_refresh VALUES(100, 'MERGE /*+ PARALLEL(16)*/', 'DIM_HC_DEPARTMENTS', NULL, 'V_DIM_HC_DEPARTMENTS', 'NETWORK,LOCATION_ID', NULL, NULL, NULL);
INSERT INTO cnf_dw_refresh VALUES(105, 'MERGE /*+ PARALLEL(16)*/', 'DIM_PROCEDURES', NULL, 'V_DIM_PROCEDURES', 'NETWORK,SRC_PROC_ID', NULL, NULL, NULL);

INSERT INTO cnf_dw_refresh VALUES(1001, 'MERGE /*+ parallel(16) index(t) */', 'EVENT', NULL, 'WITH cid AS (SELECT /*+ materialize */ NVL(etl.max_cid, 0) max_val FROM dim_hc_networks nw LEFT JOIN etl_incremental_data_load_log etl ON etl.table_name = ''EVENT'' AND etl.network = nw.network WHERE nw.network = ''CBN'') SELECT /*+ index(t idx_event_cbn_cid) */ * FROM event_cbn t WHERE cid > (SELECT max_val FROM cid)', NULL, NULL, NULL, 'ERR_EVENT');
INSERT INTO cnf_dw_refresh VALUES(1002, 'MERGE /*+ parallel(16) index(t) */', 'EVENT', NULL, 'WITH cid AS (SELECT /*+ materialize */ NVL(etl.max_cid, 0) max_val FROM dim_hc_networks nw LEFT JOIN etl_incremental_data_load_log etl ON etl.table_name = ''EVENT'' AND etl.network = nw.network WHERE nw.network = ''GP1'') SELECT /*+ index(t idx_event_gp1_cid) */ * FROM event_gp1 t WHERE cid > (SELECT max_val FROM cid)', NULL, NULL, NULL, 'ERR_EVENT');
INSERT INTO cnf_dw_refresh VALUES(1003, 'MERGE /*+ parallel(16) index(t) */', 'EVENT', NULL, 'WITH cid AS (SELECT /*+ materialize */ NVL(etl.max_cid, 0) max_val FROM dim_hc_networks nw LEFT JOIN etl_incremental_data_load_log etl ON etl.table_name = ''EVENT'' AND etl.network = nw.network WHERE nw.network = ''GP2'') SELECT /*+ index(t idx_event_gp2_cid) */ * FROM event_gp2 t WHERE cid > (SELECT max_val FROM cid)', NULL, NULL, NULL, 'ERR_EVENT');
INSERT INTO cnf_dw_refresh VALUES(1004, 'MERGE /*+ parallel(16) index(t) */', 'EVENT', NULL, 'WITH cid AS (SELECT /*+ materialize */ NVL(etl.max_cid, 0) max_val FROM dim_hc_networks nw LEFT JOIN etl_incremental_data_load_log etl ON etl.table_name = ''EVENT'' AND etl.network = nw.network WHERE nw.network = ''NBN'') SELECT /*+ index(t idx_event_nbn_cid) */ * FROM event_nbn t WHERE cid > (SELECT max_val FROM cid)', NULL, NULL, NULL, 'ERR_EVENT');
INSERT INTO cnf_dw_refresh VALUES(1005, 'MERGE /*+ parallel(16) index(t) */', 'EVENT', NULL, 'WITH cid AS (SELECT /*+ materialize */ NVL(etl.max_cid, 0) max_val FROM dim_hc_networks nw LEFT JOIN etl_incremental_data_load_log etl ON etl.table_name = ''EVENT'' AND etl.network = nw.network WHERE nw.network = ''NBX'') SELECT /*+ index(t idx_event_nbx_cid) */ * FROM event_nbx t WHERE cid > (SELECT max_val FROM cid)', NULL, NULL, NULL, 'ERR_EVENT');
INSERT INTO cnf_dw_refresh VALUES(1006, 'MERGE /*+ parallel(16) index(t) */', 'EVENT', NULL, 'WITH cid AS (SELECT /*+ materialize */ NVL(etl.max_cid, 0) max_val FROM dim_hc_networks nw LEFT JOIN etl_incremental_data_load_log etl ON etl.table_name = ''EVENT'' AND etl.network = nw.network WHERE nw.network = ''QHN'') SELECT /*+ index(t idx_event_qhn_cid) */ * FROM event_qhn t WHERE cid > (SELECT max_val FROM cid)', NULL, NULL, NULL, 'ERR_EVENT');
INSERT INTO cnf_dw_refresh VALUES(1007, 'MERGE /*+ parallel(16) index(t) */', 'EVENT', NULL, 'WITH cid AS (SELECT /*+ materialize */ NVL(etl.max_cid, 0) max_val FROM dim_hc_networks nw LEFT JOIN etl_incremental_data_load_log etl ON etl.table_name = ''EVENT'' AND etl.network = nw.network WHERE nw.network = ''SBN'') SELECT /*+ index(t idx_event_sbn_cid) */ * FROM event_sbn t WHERE cid > (SELECT max_val FROM cid)', NULL, NULL, NULL, 'ERR_EVENT');
INSERT INTO cnf_dw_refresh VALUES(1008, 'MERGE /*+ parallel(16) index(t) */', 'EVENT', NULL, 'WITH cid AS (SELECT /*+ materialize */ NVL(etl.max_cid, 0) max_val FROM dim_hc_networks nw LEFT JOIN etl_incremental_data_load_log etl ON etl.table_name = ''EVENT'' AND etl.network = nw.network WHERE nw.network = ''SMN'') SELECT /*+ index(t idx_event_smn_cid) */ * FROM event_smn t WHERE cid > (SELECT max_val FROM cid)', NULL, NULL, NULL, 'ERR_EVENT');

INSERT INTO cnf_dw_refresh VALUES(1011, 'MERGE /*+ parallel(16) index(t) */', 'PROC_EVENT', NULL, 'WITH cid AS (SELECT /*+ materialize */ NVL(etl.max_cid, 0) max_val FROM dim_hc_networks nw LEFT JOIN etl_incremental_data_load_log etl ON etl.table_name = ''PROC_EVENT'' AND etl.network = nw.network WHERE nw.network = ''CBN'') SELECT /*+ index(pe) */ pe.* FROM proc_event_cbn pe JOIN event e ON e.network = pe.network AND e.visit_id = pe.visit_id AND e.event_id = pe.event_id WHERE pe.cid > (SELECT max_val FROM cid)', NULL, NULL, NULL, NULL);
INSERT INTO cnf_dw_refresh VALUES(1012, 'MERGE /*+ parallel(16) index(t) */', 'PROC_EVENT', NULL, 'WITH cid AS (SELECT /*+ materialize */ NVL(etl.max_cid, 0) max_val FROM dim_hc_networks nw LEFT JOIN etl_incremental_data_load_log etl ON etl.table_name = ''PROC_EVENT'' AND etl.network = nw.network WHERE nw.network = ''GP1'') SELECT /*+ index(pe) */ pe.* FROM proc_event_gp1 pe JOIN event e ON e.network = pe.network AND e.visit_id = pe.visit_id AND e.event_id = pe.event_id WHERE pe.cid > (SELECT max_val FROM cid)', NULL, NULL, NULL, NULL);
INSERT INTO cnf_dw_refresh VALUES(1013, 'MERGE /*+ parallel(16) index(t) */', 'PROC_EVENT', NULL, 'WITH cid AS (SELECT /*+ materialize */ NVL(etl.max_cid, 0) max_val FROM dim_hc_networks nw LEFT JOIN etl_incremental_data_load_log etl ON etl.table_name = ''PROC_EVENT'' AND etl.network = nw.network WHERE nw.network = ''GP2'') SELECT /*+ index(pe) */ pe.* FROM proc_event_gp2 pe JOIN event e ON e.network = pe.network AND e.visit_id = pe.visit_id AND e.event_id = pe.event_id WHERE pe.cid > (SELECT max_val FROM cid)', NULL, NULL, NULL, NULL);
INSERT INTO cnf_dw_refresh VALUES(1014, 'MERGE /*+ parallel(16) index(t) */', 'PROC_EVENT', NULL, 'WITH cid AS (SELECT /*+ materialize */ NVL(etl.max_cid, 0) max_val FROM dim_hc_networks nw LEFT JOIN etl_incremental_data_load_log etl ON etl.table_name = ''PROC_EVENT'' AND etl.network = nw.network WHERE nw.network = ''NBN'') SELECT /*+ index(pe) */ pe.* FROM proc_event_nbn pe JOIN event e ON e.network = pe.network AND e.visit_id = pe.visit_id AND e.event_id = pe.event_id WHERE pe.cid > (SELECT max_val FROM cid)', NULL, NULL, NULL, NULL);
INSERT INTO cnf_dw_refresh VALUES(1015, 'MERGE /*+ parallel(16) index(t) */', 'PROC_EVENT', NULL, 'WITH cid AS (SELECT /*+ materialize */ NVL(etl.max_cid, 0) max_val FROM dim_hc_networks nw LEFT JOIN etl_incremental_data_load_log etl ON etl.table_name = ''PROC_EVENT'' AND etl.network = nw.network WHERE nw.network = ''NBX'') SELECT /*+ index(pe) */ pe.* FROM proc_event_nbx pe JOIN event e ON e.network = pe.network AND e.visit_id = pe.visit_id AND e.event_id = pe.event_id WHERE pe.cid > (SELECT max_val FROM cid)', NULL, NULL, NULL, NULL);
INSERT INTO cnf_dw_refresh VALUES(1016, 'MERGE /*+ parallel(16) index(t) */', 'PROC_EVENT', NULL, 'WITH cid AS (SELECT /*+ materialize */ NVL(etl.max_cid, 0) max_val FROM dim_hc_networks nw LEFT JOIN etl_incremental_data_load_log etl ON etl.table_name = ''PROC_EVENT'' AND etl.network = nw.network WHERE nw.network = ''QHN'') SELECT /*+ index(pe) */ pe.* FROM proc_event_qhn pe JOIN event e ON e.network = pe.network AND e.visit_id = pe.visit_id AND e.event_id = pe.event_id WHERE pe.cid > (SELECT max_val FROM cid)', NULL, NULL, NULL, NULL);
INSERT INTO cnf_dw_refresh VALUES(1017, 'MERGE /*+ parallel(16) index(t) */', 'PROC_EVENT', NULL, 'WITH cid AS (SELECT /*+ materialize */ NVL(etl.max_cid, 0) max_val FROM dim_hc_networks nw LEFT JOIN etl_incremental_data_load_log etl ON etl.table_name = ''PROC_EVENT'' AND etl.network = nw.network WHERE nw.network = ''SBN'') SELECT /*+ index(pe) */ pe.* FROM proc_event_sbn pe JOIN event e ON e.network = pe.network AND e.visit_id = pe.visit_id AND e.event_id = pe.event_id WHERE pe.cid > (SELECT max_val FROM cid)', NULL, NULL, NULL, NULL);
INSERT INTO cnf_dw_refresh VALUES(1018, 'MERGE /*+ parallel(16) index(t) */', 'PROC_EVENT', NULL, 'WITH cid AS (SELECT /*+ materialize */ NVL(etl.max_cid, 0) max_val FROM dim_hc_networks nw LEFT JOIN etl_incremental_data_load_log etl ON etl.table_name = ''PROC_EVENT'' AND etl.network = nw.network WHERE nw.network = ''SMN'') SELECT /*+ index(pe) */ pe.* FROM proc_event_smn pe JOIN event e ON e.network = pe.network AND e.visit_id = pe.visit_id AND e.event_id = pe.event_id WHERE pe.cid > (SELECT max_val FROM cid)', NULL, NULL, NULL, NULL);

INSERT INTO cnf_dw_refresh VALUES(1021, 'MERGE /*+ parallel(16) index(t) */', 'RESULT', NULL, 'WITH cid AS (SELECT /*+ materialize */ NVL(etl.max_cid, 0) max_val FROM dim_hc_networks nw LEFT JOIN etl_incremental_data_load_log etl ON etl.table_name = ''RESULT'' AND etl.network = nw.network WHERE nw.network = ''CBN'') SELECT /*+ index(r) */ r.* FROM result_cbn pe JOIN event e ON e.network = pe.network AND e.visit_id = pe.visit_id AND e.event_id = pe.event_id WHERE pe.cid > (SELECT max_val FROM cid)', NULL, NULL, NULL, NULL);
INSERT INTO cnf_dw_refresh VALUES(1022, 'MERGE /*+ parallel(16) index(t) */', 'RESULT', NULL, 'WITH cid AS (SELECT /*+ materialize */ NVL(etl.max_cid, 0) max_val FROM dim_hc_networks nw LEFT JOIN etl_incremental_data_load_log etl ON etl.table_name = ''RESULT'' AND etl.network = nw.network WHERE nw.network = ''GP1'') SELECT /*+ index(r) */ r.* FROM result_gp1 pe JOIN event e ON e.network = pe.network AND e.visit_id = pe.visit_id AND e.event_id = pe.event_id WHERE pe.cid > (SELECT max_val FROM cid)', NULL, NULL, NULL, NULL);
INSERT INTO cnf_dw_refresh VALUES(1023, 'MERGE /*+ parallel(16) index(t) */', 'RESULT', NULL, 'WITH cid AS (SELECT /*+ materialize */ NVL(etl.max_cid, 0) max_val FROM dim_hc_networks nw LEFT JOIN etl_incremental_data_load_log etl ON etl.table_name = ''RESULT'' AND etl.network = nw.network WHERE nw.network = ''GP2'') SELECT /*+ index(r) */ r.* FROM result_gp2 pe JOIN event e ON e.network = pe.network AND e.visit_id = pe.visit_id AND e.event_id = pe.event_id WHERE pe.cid > (SELECT max_val FROM cid)', NULL, NULL, NULL, NULL);
INSERT INTO cnf_dw_refresh VALUES(1024, 'MERGE /*+ parallel(16) index(t) */', 'RESULT', NULL, 'WITH cid AS (SELECT /*+ materialize */ NVL(etl.max_cid, 0) max_val FROM dim_hc_networks nw LEFT JOIN etl_incremental_data_load_log etl ON etl.table_name = ''RESULT'' AND etl.network = nw.network WHERE nw.network = ''NBN'') SELECT /*+ index(r) */ r.* FROM result_nbn pe JOIN event e ON e.network = pe.network AND e.visit_id = pe.visit_id AND e.event_id = pe.event_id WHERE pe.cid > (SELECT max_val FROM cid)', NULL, NULL, NULL, NULL);
INSERT INTO cnf_dw_refresh VALUES(1025, 'MERGE /*+ parallel(16) index(t) */', 'RESULT', NULL, 'WITH cid AS (SELECT /*+ materialize */ NVL(etl.max_cid, 0) max_val FROM dim_hc_networks nw LEFT JOIN etl_incremental_data_load_log etl ON etl.table_name = ''RESULT'' AND etl.network = nw.network WHERE nw.network = ''NBX'') SELECT /*+ index(r) */ r.* FROM result_nbx pe JOIN event e ON e.network = pe.network AND e.visit_id = pe.visit_id AND e.event_id = pe.event_id WHERE pe.cid > (SELECT max_val FROM cid)', NULL, NULL, NULL, NULL);
INSERT INTO cnf_dw_refresh VALUES(1026, 'MERGE /*+ parallel(16) index(t) */', 'RESULT', NULL, 'WITH cid AS (SELECT /*+ materialize */ NVL(etl.max_cid, 0) max_val FROM dim_hc_networks nw LEFT JOIN etl_incremental_data_load_log etl ON etl.table_name = ''RESULT'' AND etl.network = nw.network WHERE nw.network = ''QHN'') SELECT /*+ index(r) */ r.* FROM result_qhn pe JOIN event e ON e.network = pe.network AND e.visit_id = pe.visit_id AND e.event_id = pe.event_id WHERE pe.cid > (SELECT max_val FROM cid)', NULL, NULL, NULL, NULL);
INSERT INTO cnf_dw_refresh VALUES(1027, 'MERGE /*+ parallel(16) index(t) */', 'RESULT', NULL, 'WITH cid AS (SELECT /*+ materialize */ NVL(etl.max_cid, 0) max_val FROM dim_hc_networks nw LEFT JOIN etl_incremental_data_load_log etl ON etl.table_name = ''RESULT'' AND etl.network = nw.network WHERE nw.network = ''SBN'') SELECT /*+ index(r) */ r.* FROM result_sbn pe JOIN event e ON e.network = pe.network AND e.visit_id = pe.visit_id AND e.event_id = pe.event_id WHERE pe.cid > (SELECT max_val FROM cid)', NULL, NULL, NULL, NULL);
INSERT INTO cnf_dw_refresh VALUES(1028, 'MERGE /*+ parallel(16) index(t) */', 'RESULT', NULL, 'WITH cid AS (SELECT /*+ materialize */ NVL(etl.max_cid, 0) max_val FROM dim_hc_networks nw LEFT JOIN etl_incremental_data_load_log etl ON etl.table_name = ''RESULT'' AND etl.network = nw.network WHERE nw.network = ''SMN'') SELECT /*+ index(r) */ r.* FROM result_smn pe JOIN event e ON e.network = pe.network AND e.visit_id = pe.visit_id AND e.event_id = pe.event_id WHERE pe.cid > (SELECT max_val FROM cid)', NULL, NULL, NULL, NULL);

COMMIT;
