CREATE TABLE dim_patients
(
  PATIENT_KEY                VARCHAR2(255 BYTE),
  NETWORK                    VARCHAR2(6 BYTE),
  PATIENT_ID                 NUMBER(12) NOT NULL,
  ARCHIVE_NUMBER             NUMBER(12),
  ARCHIVE_TIME               DATE,
  NAME                       VARCHAR2(100 BYTE),
  PCP_PROVIDER_ID            NUMBER(12),
  PCP_PROVIDER_NAME          VARCHAR2(60 BYTE),
  TITLE_ID                   NUMBER(12),
  MEDICAL_RECORD_NUMBER      VARCHAR2(512 BYTE),
  SEX                        VARCHAR2(8 BYTE),
  BIRTHDATE                  DATE,
  DATE_OF_DEATH              DATE,
  APT_SUITE                  VARCHAR2(1024 BYTE),
  STREET_ADDRESS             VARCHAR2(1024 BYTE),
  CITY                       VARCHAR2(50 BYTE),
  STATE                      VARCHAR2(50 BYTE),
  COUNTRY                    VARCHAR2(50 BYTE),
  MAILING_CODE               VARCHAR2(50 BYTE),
  MARITAL_STATUS_ID          NUMBER(12),
  MARITAL_STATUS_DESC        VARCHAR2(100 BYTE),
  RACE_ID                    NUMBER(12),
  RACE_DESC                  VARCHAR2(100 BYTE),
  RELIGION_ID                NUMBER(12),
  RELIGION_DESC              VARCHAR2(100 BYTE),
  FREE_TEXT_RELIGION         VARCHAR2(100 BYTE),
  OCCUPATION_ID              NUMBER(12),
  OCCUPATION_DESC            VARCHAR2(100 BYTE),
  FREE_TEXT_OCCUPATION       VARCHAR2(100 BYTE),
  EMPLOYER_ID                NUMBER(12),
  EMPLOYER_NAME              VARCHAR2(100 BYTE),
  FREE_TEXT_EMPLOYER         VARCHAR2(150 BYTE),
  MOTHER_PATIENT_ID          NUMBER(12),
  COLLAPSED_INTO_PATIENT_ID  NUMBER(12),
  SOCIAL_SECURITY_NUMBER     VARCHAR2(15 BYTE),
  LIFECARE_VISIT_ID          NUMBER(12),
  CONFIDENTIAL_FLAG          VARCHAR2(1 BYTE),
  HOME_PHONE                 VARCHAR2(50 BYTE),
  DAY_PHONE                  VARCHAR2(50 BYTE),
  SMOKER_FLAG                VARCHAR2(1 BYTE),
  CURRENT_LOCATION           VARCHAR2(55 BYTE),
  SEC_LANG_NAME              VARCHAR2(100 BYTE),
  ADDR_STRING                VARCHAR2(256 BYTE),
  BLOCK_CODE                 VARCHAR2(256 BYTE),
  LAST_EDIT_TIME             DATE,
  COUNTY                     VARCHAR2(50 BYTE),
  SUB_BUILDING_NAME          VARCHAR2(256 BYTE),
  BUILDING_NAME              VARCHAR2(256 BYTE),
  BUILDING_NBR               VARCHAR2(256 BYTE),
  DEPENDENT_STREET           VARCHAR2(256 BYTE),
  DEPENDENT_LOCALITY         VARCHAR2(256 BYTE),
  UK_NHS_NUMBER              NUMBER(10),
  UK_HA_RES_CODE             VARCHAR2(8 BYTE),
  UK_PCT_RES_CODE            VARCHAR2(8 BYTE),
  HEAD_OF_HOUSE_PATIENT_ID   NUMBER(12),
  PATIENT_ARCHIVE_TYPE_ID    NUMBER(12),
  ARCHIVE_SOURCE_ID          NUMBER(12),
  CURRENT_FLAG               NUMBER(1) DEFAULT 1 NOT NULL CHECK(current_flag IN (0,1)),
  EFFECTIVE_FROM             DATE DEFAULT SYSDATE NOT NULL,
  EFFECTIVE_TO               DATE DEFAULT DATE '9999-12-31',
  EPIC_FLAG                  CHAR(1 BYTE) DEFAULT 'N',
  SOURCE                     VARCHAR2(30 BYTE),
  LOAD_DT                    DATE DEFAULT TRUNC(SYSDATE),
  LOADED_BY                  VARCHAR2(30 BYTE) DEFAULT SYS_CONTEXT('USERENV','OS_USER')
)
COMPRESS BASIC 
PARTITION BY LIST (NETWORK)
(  
  PARTITION CBN VALUES ('CBN'),
  PARTITION GP1 VALUES ('GP1'),
  PARTITION GP2 VALUES ('GP2'),
  PARTITION NBN VALUES ('NBN'),
  PARTITION NBX VALUES ('NBX'),
  PARTITION QHN VALUES ('QHN'),
  PARTITION SBN VALUES ('SBN'),
  PARTITION SMN VALUES ('SMN')
);

ALTER TABLE dim_patients ADD CONSTRAINT pk_dim_patients PRIMARY KEY(patient_key) USING INDEX
(
  CREATE UNIQUE INDEX pk_dim_patients ON dim_patients(patient_key) PARALLEL 16
);

CREATE UNIQUE INDEX uk_dim_patient ON dim_patients
(
  CASE WHEN current_flag = 1 THEN patient_id END,
  CASE WHEN current_flag = 1 THEN network END
) PARALLEL 16;

ALTER INDEX pk_dim_patients NOPARALLEL;
ALTER INDEX uk_dim_patient NOPARALLEL;

CREATE OR REPLACE SYNONYM dim_patient FOR dim_patients;