INSERT INTO meta_lists VALUES(33, 'MEDICATIONS:DIABETES', 'List of Medications for treating Diabetes', 'MED', 'LIKE');

INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%acarbose%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%actoplus%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%actos%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%albiglutide%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%alogliptin %', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%amaryl%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%apidra%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%avandamet%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%avandaryl%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%avandia%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%bromocriptine %', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%bydureon%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%byetta%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%canagliflozin%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%chlorpropamide %', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%dapagliflozin %', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%diabeta%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%diabinese%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%duetact%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%dulaglutide %', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%empagliflozin%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%exenatide %', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%farxiga%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%flexpen%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%fortamet%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%gliclazide%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%glimepiride %', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%glipizide %', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%glucophage%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%glucotrol%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%glucovance%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%glumetza%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%glyburide%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%glynase%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%glyset%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%glyxambi%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%humalog%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%humulin  %', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%insulin %', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%invokamet%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%invokana%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%janumet%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%januvia%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%jardiance%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%jentadueto%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%juvisync%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%kazano%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%kombiglyze%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%lantus%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%levemir%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%linagliptin%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%liraglutide%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%metaglip%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%metformin%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%micronase%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%miglitol %', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%nateglinide%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%nesina%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%novolin%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%novolog%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%onglyza%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%orinase%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%oseni%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%parlodel%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%pioglitazone%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%pramlintide %', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%prandimet%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%prandin%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%precose%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%repaglinide%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%riomet%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%rosiglitazone%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%ryzodeg %', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%saxagliptin%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%simvastatin %', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%sitagliptin%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%starlix%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%symlinpen%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%synjardy%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%tanzeum%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%tol-tab%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%tolazamide %', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%tolbutamide %', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%tolinase%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%toujeo%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%tradjenta%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%tresiba%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%trulicity%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%victoza%', NULL, NULL);
INSERT INTO meta_list_items VALUES (33, 'ALL', 'NONE', '%xigduo%', NULL, NULL);

COMMIT;