INSERT INTO meta_criteria VALUES(33, 'MEDICATIONS:DIABETES', 'List of Medications for treating Diabetes');

INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%acarbose%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%actoplus%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%actos%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%albiglutide%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%alogliptin %', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%amaryl%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%apidra%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%avandamet%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%avandaryl%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%avandia%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%bromocriptine %', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%bydureon%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%byetta%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%canagliflozin%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%chlorpropamide %', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%dapagliflozin %', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%diabeta%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%diabinese%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%duetact%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%dulaglutide %', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%empagliflozin%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%exenatide %', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%farxiga%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%flexpen%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%fortamet%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%gliclazide%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%glimepiride %', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%glipizide %', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%glucophage%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%glucotrol%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%glucovance%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%glumetza%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%glyburide%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%glynase%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%glyset%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%glyxambi%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%humalog%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%humulin  %', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%insulin %', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%invokamet%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%invokana%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%janumet%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%januvia%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%jardiance%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%jentadueto%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%juvisync%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%kazano%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%kombiglyze%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%lantus%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%levemir%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%linagliptin%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%liraglutide%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%metaglip%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%metformin%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%micronase%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%miglitol %', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%nateglinide%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%nesina%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%novolin%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%novolog%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%onglyza%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%orinase%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%oseni%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%parlodel%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%pioglitazone%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%pramlintide %', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%prandimet%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%prandin%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%precose%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%repaglinide%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%riomet%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%rosiglitazone%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%ryzodeg %', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%saxagliptin%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%simvastatin %', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%sitagliptin%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%starlix%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%symlinpen%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%synjardy%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%tanzeum%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%tol-tab%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%tolazamide %', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%tolbutamide %', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%tolinase%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%toujeo%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%tradjenta%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%tresiba%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%trulicity%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%victoza%', 'Diabetes medication', 'MED', 'LIKE', 'I');
INSERT INTO meta_conditions VALUES(33, 'ALL', 'NONE', '%xigduo%', 'Diabetes medication', 'MED', 'LIKE', 'I');

COMMIT;