INSERT INTO meta_lists VALUES(34, 'MEDICATIONS:ANTIPSYCHOTIC', 'List of Medications for treating Psychotic Disorders', 'MED', 'LIKE');

INSERT INTO meta_list_items VALUES (34, 'ALL', 'NONE', '%abilify%', NULL, NULL);
INSERT INTO meta_list_items VALUES (34, 'ALL', 'NONE', '%amitriptyline%', NULL, NULL);
INSERT INTO meta_list_items VALUES (34, 'ALL', 'NONE', '%aripiprazole%', NULL, NULL);
INSERT INTO meta_list_items VALUES (34, 'ALL', 'NONE', '%asenapine%', NULL, NULL);
INSERT INTO meta_list_items VALUES (34, 'ALL', 'NONE', '%cariprazine%', NULL, NULL);
INSERT INTO meta_list_items VALUES (34, 'ALL', 'NONE', '%chlorpromazine%', NULL, NULL);
INSERT INTO meta_list_items VALUES (34, 'ALL', 'NONE', '%clozapine%', NULL, NULL);
INSERT INTO meta_list_items VALUES (34, 'ALL', 'NONE', '%clozaril%', NULL, NULL);
INSERT INTO meta_list_items VALUES (34, 'ALL', 'NONE', '%compazine %', NULL, NULL);
INSERT INTO meta_list_items VALUES (34, 'ALL', 'NONE', '%compro %', NULL, NULL);
INSERT INTO meta_list_items VALUES (34, 'ALL', 'NONE', '%etrafon,%', NULL, NULL);
INSERT INTO meta_list_items VALUES (34, 'ALL', 'NONE', '%fanapt%', NULL, NULL);
INSERT INTO meta_list_items VALUES (34, 'ALL', 'NONE', '%fluphenazine%', NULL, NULL);
INSERT INTO meta_list_items VALUES (34, 'ALL', 'NONE', '%geodon%', NULL, NULL);
INSERT INTO meta_list_items VALUES (34, 'ALL', 'NONE', '%haldol%', NULL, NULL);
INSERT INTO meta_list_items VALUES (34, 'ALL', 'NONE', '%haloperidol%', NULL, NULL);
INSERT INTO meta_list_items VALUES (34, 'ALL', 'NONE', '%iloperidone%', NULL, NULL);
INSERT INTO meta_list_items VALUES (34, 'ALL', 'NONE', '%invega%', NULL, NULL);
INSERT INTO meta_list_items VALUES (34, 'ALL', 'NONE', '%latuda%', NULL, NULL);
INSERT INTO meta_list_items VALUES (34, 'ALL', 'NONE', '%loxapine%', NULL, NULL);
INSERT INTO meta_list_items VALUES (34, 'ALL', 'NONE', '%loxitane%', NULL, NULL);
INSERT INTO meta_list_items VALUES (34, 'ALL', 'NONE', '%lurasidone%', NULL, NULL);
INSERT INTO meta_list_items VALUES (34, 'ALL', 'NONE', '%mellaril%', NULL, NULL);
INSERT INTO meta_list_items VALUES (34, 'ALL', 'NONE', '%moban%', NULL, NULL);
INSERT INTO meta_list_items VALUES (34, 'ALL', 'NONE', '%molindone%', NULL, NULL);
INSERT INTO meta_list_items VALUES (34, 'ALL', 'NONE', '%navane%', NULL, NULL);
INSERT INTO meta_list_items VALUES (34, 'ALL', 'NONE', '%olanzapine%', NULL, NULL);
INSERT INTO meta_list_items VALUES (34, 'ALL', 'NONE', '%orap%', NULL, NULL);
INSERT INTO meta_list_items VALUES (34, 'ALL', 'NONE', '%oxilapine%', NULL, NULL);
INSERT INTO meta_list_items VALUES (34, 'ALL', 'NONE', '%paliperidone%', NULL, NULL);
INSERT INTO meta_list_items VALUES (34, 'ALL', 'NONE', '%permitil%', NULL, NULL);
INSERT INTO meta_list_items VALUES (34, 'ALL', 'NONE', '%perphenazine%', NULL, NULL);
INSERT INTO meta_list_items VALUES (34, 'ALL', 'NONE', '%pimozide%', NULL, NULL);
INSERT INTO meta_list_items VALUES (34, 'ALL', 'NONE', '%prochlorperazine%', NULL, NULL);
INSERT INTO meta_list_items VALUES (34, 'ALL', 'NONE', '%procomp%', NULL, NULL);
INSERT INTO meta_list_items VALUES (34, 'ALL', 'NONE', '%prolixin%', NULL, NULL);
INSERT INTO meta_list_items VALUES (34, 'ALL', 'NONE', '%promapar%', NULL, NULL);
INSERT INTO meta_list_items VALUES (34, 'ALL', 'NONE', '%quetiapine%', NULL, NULL);
INSERT INTO meta_list_items VALUES (34, 'ALL', 'NONE', '%risperdal%', NULL, NULL);
INSERT INTO meta_list_items VALUES (34, 'ALL', 'NONE', '%risperidone%', NULL, NULL);
INSERT INTO meta_list_items VALUES (34, 'ALL', 'NONE', '%saphris%', NULL, NULL);
INSERT INTO meta_list_items VALUES (34, 'ALL', 'NONE', '%seroquel %', NULL, NULL);
INSERT INTO meta_list_items VALUES (34, 'ALL', 'NONE', '%seroquel%', NULL, NULL);
INSERT INTO meta_list_items VALUES (34, 'ALL', 'NONE', '%stelazine%', NULL, NULL);
INSERT INTO meta_list_items VALUES (34, 'ALL', 'NONE', '%sycrest%', NULL, NULL);
INSERT INTO meta_list_items VALUES (34, 'ALL', 'NONE', '%symbyax%', NULL, NULL);
INSERT INTO meta_list_items VALUES (34, 'ALL', 'NONE', '%thioridazine%', NULL, NULL);
INSERT INTO meta_list_items VALUES (34, 'ALL', 'NONE', '%thiothixene%', NULL, NULL);
INSERT INTO meta_list_items VALUES (34, 'ALL', 'NONE', '%thorazine%', NULL, NULL);
INSERT INTO meta_list_items VALUES (34, 'ALL', 'NONE', '%triavil%', NULL, NULL);
INSERT INTO meta_list_items VALUES (34, 'ALL', 'NONE', '%trifluoperazine%', NULL, NULL);
INSERT INTO meta_list_items VALUES (34, 'ALL', 'NONE', '%trilafon%', NULL, NULL);
INSERT INTO meta_list_items VALUES (34, 'ALL', 'NONE', '%vraylar%', NULL, NULL);
INSERT INTO meta_list_items VALUES (34, 'ALL', 'NONE', '%ziprasidone%', NULL, NULL);
INSERT INTO meta_list_items VALUES (34, 'ALL', 'NONE', '%zyprexa%', NULL, NULL);

COMMIT;