RENAME PATIENT TO BKP_PATIENT;

CREATE TABLE patient
(
  NETWORK                    CHAR(3 BYTE),
  PATIENT_ID                 NUMBER(12) NOT NULL,
  NAME                       VARCHAR2(100 BYTE),
  TITLE_ID                   NUMBER(12),
  MEDICAL_RECORD_NUMBER      VARCHAR2(512 BYTE),
  SEX                        VARCHAR2(8 BYTE),
  BIRTHDATE                  DATE,
  DATE_OF_DEATH              DATE,
  APT_SUITE                  VARCHAR2(1024 BYTE),
  STREET_ADDRESS             VARCHAR2(1024 BYTE),
  CITY                       VARCHAR2(50 BYTE),
  STATE                      VARCHAR2(50 BYTE),
  COUNTRY                    VARCHAR2(50 BYTE),
  MAILING_CODE               VARCHAR2(50 BYTE),
  MARITAL_STATUS_ID          NUMBER(12),
  RACE_ID                    NUMBER(12),
  RELIGION_ID                NUMBER(12),
  FREE_TEXT_RELIGION         VARCHAR2(100 BYTE),
  OCCUPATION_ID              NUMBER(12),
  FREE_TEXT_OCCUPATION       VARCHAR2(100 BYTE),
  EMPLOYER_ID                NUMBER(12),
  FREE_TEXT_EMPLOYER         VARCHAR2(150 BYTE),
  MOTHER_PATIENT_ID          NUMBER(12),
  COLLAPSED_INTO_PATIENT_ID  NUMBER(12),
  SOCIAL_SECURITY_NUMBER     VARCHAR2(15 BYTE),
  LIFECARE_VISIT_ID          NUMBER(12),
  CONFIDENTIAL_FLAG          VARCHAR2(1 BYTE),
  HOME_PHONE                 VARCHAR2(50 BYTE),
  DAY_PHONE                  VARCHAR2(50 BYTE),
  SMOKER_FLAG                VARCHAR2(1 BYTE),
  CURRENT_LOCATION           VARCHAR2(128 BYTE),
  SEC_LANG_NAME              VARCHAR2(100 BYTE),
  ADDR_STRING                VARCHAR2(256 BYTE),
  BLOCK_CODE                 VARCHAR2(256 BYTE),
  LAST_EDIT_TIME             DATE,
  COUNTY                     VARCHAR2(50 BYTE),
  SUB_BUILDING_NAME          VARCHAR2(256 BYTE),
  BUILDING_NAME              VARCHAR2(256 BYTE),
  BUILDING_NBR               VARCHAR2(256 BYTE),
  DEPENDENT_STREET           VARCHAR2(256 BYTE),
  DEPENDENT_LOCALITY         VARCHAR2(256 BYTE),
  UK_NHS_NUMBER              NUMBER(10),
  UK_HA_RES_CODE             VARCHAR2(8 BYTE),
  UK_PCT_RES_CODE            VARCHAR2(8 BYTE),
  HEAD_OF_HOUSE_PATIENT_ID   NUMBER(12)
) COMPRESS BASIC
PARTITION BY LIST(network)
(
  PARTITION cbn VALUES('CBN'),
  PARTITION gp1 VALUES('GP1'),
  PARTITION gp2 VALUES('GP2'),
  PARTITION nbn VALUES('NBN'),
  PARTITION nbx VALUES('NBX'),
  PARTITION qhn VALUES('QHN'),
  PARTITION sbn VALUES('SBN'),
  PARTITION smn VALUES('SMN')
);

ALTER TABLE patient ADD CONSTRAINT pk_patient PRIMARY KEY(patient_id, network) USING INDEX LOCAL; 

GRANT SELECT ON patient TO PUBLIC;
