exec dbm.drop_tables('VALUE_DECODE');

CREATE TABLE value_decode
(
  NETWORK           CHAR(3 BYTE),
  DECODE_SOURCE_ID  VARCHAR2(100 BYTE) NOT NULL,
  ENCODED_VALUE     VARCHAR2(60 BYTE) NOT NULL,
  DECODED_VALUE     VARCHAR2(1300 BYTE),
  CONSTRAINT pk_value_decode PRIMARY KEY(network, decode_source_id, encoded_value) 
) ORGANIZATION INDEX;

GRANT SELECT ON VALUE_DECODE TO PUBLIC;
