CREATE TABLE visit
(
  NETWORK                        CHAR(3 BYTE),
  VISIT_ID                       NUMBER(12) NOT NULL,
  VISIT_NUMBER                   VARCHAR2(40 BYTE),
  PATIENT_ID                     NUMBER(12),
  VISIT_TYPE_ID                  NUMBER(12),
  VISIT_SUBTYPE_ID               NUMBER(12),
  VISIT_STATUS_ID                NUMBER(12),
  FACILITY_ID                    NUMBER(12),
  ATTENDING_EMP_PROVIDER_ID      NUMBER(12),
  RESIDENT_EMP_PROVIDER_ID       NUMBER(12),
  ADMISSION_DATE_TIME            DATE,
  DISCHARGE_DATE_TIME            DATE,
  DISCHARGE_TYPE_ID              NUMBER(12),
  MARITAL_STATUS_ID              NUMBER(12),
  RELIGION_ID                    NUMBER(12),
  FREE_TEXT_RELIGION             VARCHAR2(100 BYTE),
  FINANCIAL_CLASS_ID             NUMBER(12),
  OCCUPATION_ID                  NUMBER(12),
  FREE_TEXT_OCCUPATION           VARCHAR2(100 BYTE),
  EMPLOYER_ID                    NUMBER(12),
  FREE_TEXT_EMPLOYER             VARCHAR2(100 BYTE),
  PHYSICIAN_SERVICE_ID           VARCHAR2(12 BYTE),
  LOCATION_ID                    VARCHAR2(12 BYTE),
  ADDL_RESP_EMP_PROVIDER_ID      NUMBER(12),
  ADDL_RESP_STRING               VARCHAR2(100 BYTE),
  ATTENDING_STRING               VARCHAR2(100 BYTE),
  RESIDENT_STRING                VARCHAR2(100 BYTE),
  LAST_LOCATION                  VARCHAR2(128 BYTE),
  ADDL_RESP_RESIDENT_SERVICE_ID  NUMBER(12),
  TRIAGE_ACUITY_ID               NUMBER(12),
  SERIES_VISIT_FLAG              VARCHAR2(5 BYTE),
  NEWBORN_FLAG                   VARCHAR2(5 BYTE),
  MOTHER_VISIT_ID                NUMBER(12),
  SCHEDULED_PROC_ID              NUMBER(12),
  SCHEDULED_EVENT_ID             NUMBER(12),
  UK_HA_RES_CODE                 VARCHAR2(8 BYTE),
  UK_PCT_RES_CODE                VARCHAR2(8 BYTE),
  INTER_FACILITY_TO_VISIT_ID     NUMBER(12),
  INTER_FACILITY_FROM_VISIT_ID   NUMBER(12),
  CID                            NUMBER(14),
  CONSTRAINT pk_visit PRIMARY KEY(visit_id, network) USING INDEX LOCAL
)
COMPRESS BASIC
PARTITION BY LIST(network)
SUBPARTITION BY HASH(visit_id)
(
  PARTITION cbn VALUES('CBN'),
  PARTITION gp1 VALUES('GP1'),
  PARTITION gp2 VALUES('GP2'),
  PARTITION nbn VALUES('NBN'),
  PARTITION nbx VALUES('NBX'),
  PARTITION qhn VALUES('QHN'),
  PARTITION sbn VALUES('SBN'),
  PARTITION smn VALUES('SMN')
);

CREATE INDEX idx_visit_cid ON visit(cid, network) LOCAL PARALLEL 16;
 
