exec dbm.drop_tables('DSRIP_REPORT_TR016_EPIC');

CREATE TABLE dsrip_report_tr016_epic
(
  report_period_start_dt          DATE NOT NULL,
  network                         CHAR(3) NOT NULL,
  facility_name                   VARCHAR2(255) NOT NULL,
  location_id                     NUMBER(18) NOT NULL,
  location_name                   VARCHAR2(80) NOT NULL,
  mrn_empi                        VARCHAR2(100) NOT NULL,
  location_mrn                    VARCHAR2(100) NOT NULL,
  pat_name                        VARCHAR2(200) NOT NULL,
  birth_date                      TIMESTAMP(6),
  age_years                       INTEGER,
  address_line_1                  VARCHAR2(50),
  address_line_2                  VARCHAR2(50),
  address_state                   VARCHAR2(254),
  address_zip                     VARCHAR2(60),
  home_phone                      VARCHAR2(192),
  last_primary_care_visit_dt      TIMESTAMP(6),
  last_primary_care_vst_dep_nm    VARCHAR2(254),
  pcp_general_name                VARCHAR2(200),
  contactdate                     TIMESTAMP(6),
  hospital_discharge_date         TIMESTAMP(6),
  encounter_type                  VARCHAR2(254),
  inspayor1                       VARCHAR2(254),
  inspayor2                       VARCHAR2(254),
  inspayor3                       VARCHAR2(254),
  icd10_codes                     VARCHAR2(510) NOT NULL,
  antipsychotic_med_order_dt      TIMESTAMP(6),
  antipsychotic_medication_name   VARCHAR2(510),
  hemoglobin_order_time           TIMESTAMP(6),
  hemoglobin_result_time          TIMESTAMP(6),
  hemoglobin_result_value         VARCHAR2(254),
  numerator_flag_hemoglobin_test  INTEGER,
  last_behav_health_visit_dt      TIMESTAMP(6),
  last_behav_health_visit_dep_nm  VARCHAR2(254),
  CONSTRAINT dsrip_report_tr016_epic_pk PRIMARY KEY(report_period_start_dt, mrn_empi)
);