DROP TABLE tst_ok_tr016_a1c_glucose_lvl PURGE;

CREATE TABLE tst_ok_tr016_a1c_glucose_lvl
(
  NETWORK            VARCHAR2(3) NOT NULL,
  FACILITY_ID        NUMBER(12) NOT NULL,
  PATIENT_ID         NUMBER(12) NOT NULL,
  VISIT_ID           NUMBER(12) NOT NULL,
  ADMISSION_DT       DATE,
  DISCHARGE_DT       DATE,
  TEST_TYPE_ID       NUMBER(6) NOT NULL,
  EVENT_ID           NUMBER(12) NOT NULL,
  RESULT_DT          DATE NOT NULL,
  DATA_ELEMENT_ID    VARCHAR2(25) NOT NULL,
  DATA_ELEMENT_NAME  VARCHAR2(120) NOT NULL,
  RESULT_VALUE       VARCHAR2(1023) NOT NULL
) COMPRESS BASIC ;

GRANT SELECT ON tst_ok_tr016_a1c_glucose_lvl TO PUBLIC;