CREATE OR REPLACE SYNONYM EDD_STG_TIME FOR eddashboard.EDD_STG_TIME;
CREATE OR REPLACE SYNONYM EDD_STG_PATIENTVISIT_INFO FOR eddashboard.EDD_STG_PATIENTVISIT_INFO;
CREATE OR REPLACE SYNONYM EDD_STG_PATIENTVISITCORPORATE FOR eddashboard.EDD_STG_PATIENTVISITCORPORATE;
CREATE OR REPLACE SYNONYM EDD_STG_FACILITIES FOR eddashboard.EDD_STG_FACILITIES;
CREATE OR REPLACE SYNONYM EDD_STG_DISPOSITIONS FOR eddashboard.EDD_STG_DISPOSITIONS;