-- From Steve:

SELECT /*+ PARALLEL (32) */
  SUBSTR(ORA_DATABASE_NAME, 1, 3) AS NETWORK,
  ECP.VISIT_ID,
  ECP.EVENT_ID,
  VV.PATIENT_ID,
  VV.FACILITY_ID,
  EE.DATE_TIME AS EVENT_DATE_TIME,
  'CPT4 Procedure Code' LABEL,
  'CPT4' TYPE,
  ECP.CODE_NBR AS PROBLEM_CPT_NBR,
  TRIM(ECP.CPT4_PROC_CODE) AS CODE,
  CP.NAME AS DESCRIPTION,
  0 AS STATUS_ID,
  'active' AS STATUS_DESC
FROM UD_MASTER.CPT4_PROC CP
JOIN UD_MASTER.EVENT_CPT4_PROC ECP ON ECP.CPT4_PROC_CODE = CP.CPT4_PROC_CODE 
JOIN UD_MASTER.VISIT VV ON VV.VISIT_ID = ECP.VISIT_ID
JOIN UD_MASTER.EVENT EE ON EE.VISIT_ID = ECP.VISIT_ID AND EE.EVENT_ID = ECP.EVENT_ID
UNION ALL
SELECT /*+ PARALLEL (32) */
  DISTINCT
  SUBSTR(ORA_DATABASE_NAME, 1, 3),
  AP.VISIT_ID,
  AP.EVENT_ID,
  PROB.PATIENT_ID,
  VV.FACILITY_ID,
  EE.DATE_TIME AS EVENT_DATE_TIME,
  CASE WHEN RF.NAME IN ('ICD-10 CM', 'ICD-9 Diagnosis', 'ICD-9 Procedure') THEN 'Primary Diagnosis' ELSE RF.NAME END LABEL,
  'ICD' TYPE,
  PROB.PROBLEM_NUMBER AS PROBLEM_CPT_NBR,
  PID.ICD_DIAGNOSIS_CODE AS CODE,
  PROB.PROBLEM_DESCRIPTION AS DESCRIPTION,
  PROB.STATUS_ID,
  PS.NAME AS STATUS_DESC
FROM UD_MASTER.PROBLEM PROB
JOIN UD_MASTER.ACTIVE_PROBLEM AP ON AP.PATIENT_ID = PROB.PATIENT_ID AND AP.PROBLEM_NUMBER = PROB.PROBLEM_NUMBER 
JOIN UD_MASTER.RESULT_FIELD RF ON RF.DATA_ELEMENT_ID = AP.DATA_ELEMENT_ID
JOIN UD_MASTER.PROBLEM_ICD_DIAGNOSIS PID ON PID.PROBLEM_NUMBER = PROB.PROBLEM_NUMBER AND PID.PATIENT_ID = PROB.PATIENT_ID 
JOIN UD_MASTER.EVENT EE ON EE.VISIT_ID = AP.VISIT_ID AND EE.EVENT_ID = AP.EVENT_ID
JOIN UD_MASTER.VISIT VV ON VV.VISIT_ID = EE.VISIT_ID
JOIN UD_MASTER.PROBLEM_STATUS PS ON PS.STATUS_ID = PROB.STATUS_ID 
GROUP BY PROB.PATIENT_ID,
  AP.VISIT_ID,
  AP.EVENT_ID,
  PROB.PATIENT_ID,
  VV.FACILITY_ID,
  EE.DATE_TIME,
  PROB.PROBLEM_DESCRIPTION,
  PROB.PROBLEM_NUMBER,
  RF.NAME,
  PID.ICD_DIAGNOSIS_CODE,
  PROB.STATUS_ID,
  PS.NAME;


select --+ parallel(16)
  network, visit_id, event_id
from event_cpt4_proc
minus
select --+ parallel(16)
  network, visit_id, event_id
from proc_event;
