prompt - 01.PKG_DB_MAINTENANCE.pks
@@01.PKG_DB_MAINTENANCE.pks

prompt - 02.V_TABLE_PARTITION_INFO.sql
@@02.V_TABLE_PARTITION_INFO.sql

prompt - 03.V_INDEX_PARTITION_INFO.sql
@@03.V_INDEX_PARTITION_INFO.sql

prompt - 04.PKG_DB_MAINTENANCE.pkb
@@04.PKG_DB_MAINTENANCE.pkb
