DROP TABLE VISIT PURGE;

CREATE TABLE visit
(
  NETWORK                        CHAR(3 BYTE) NOT NULL,
  VISIT_ID                       NUMBER(12) NOT NULL,
  VISIT_NUMBER                   VARCHAR2(40 BYTE),
  PATIENT_ID                     NUMBER(12),
  VISIT_TYPE_ID                  NUMBER(12),
  VISIT_SUBTYPE_ID               NUMBER(12),
  VISIT_STATUS_ID                NUMBER(12),
  FACILITY_ID                    NUMBER(12),
  ATTENDING_EMP_PROVIDER_ID      NUMBER(12),
  RESIDENT_EMP_PROVIDER_ID       NUMBER(12),
  ADMISSION_DATE_TIME            DATE,
  DISCHARGE_DATE_TIME            DATE,
  DISCHARGE_TYPE_ID              NUMBER(12),
  MARITAL_STATUS_ID              NUMBER(12),
  RELIGION_ID                    NUMBER(12),
  FREE_TEXT_RELIGION             VARCHAR2(100 BYTE),
  FINANCIAL_CLASS_ID             NUMBER(12),
  OCCUPATION_ID                  NUMBER(12),
  FREE_TEXT_OCCUPATION           VARCHAR2(100 BYTE),
  EMPLOYER_ID                    NUMBER(12),
  FREE_TEXT_EMPLOYER             VARCHAR2(100 BYTE),
  PHYSICIAN_SERVICE_ID           VARCHAR2(12 BYTE),
  LOCATION_ID                    VARCHAR2(12 BYTE),
  ADDL_RESP_EMP_PROVIDER_ID      NUMBER(12),
  ADDL_RESP_STRING               VARCHAR2(100 BYTE),
  ATTENDING_STRING               VARCHAR2(100 BYTE),
  RESIDENT_STRING                VARCHAR2(100 BYTE),
  LAST_LOCATION                  VARCHAR2(128 BYTE),
  ADDL_RESP_RESIDENT_SERVICE_ID  NUMBER(12),
  TRIAGE_ACUITY_ID               NUMBER(12),
  SERIES_VISIT_FLAG              VARCHAR2(5 BYTE),
  NEWBORN_FLAG                   VARCHAR2(5 BYTE),
  MOTHER_VISIT_ID                NUMBER(12),
  SCHEDULED_PROC_ID              NUMBER(12),
  SCHEDULED_EVENT_ID             NUMBER(12),
  UK_HA_RES_CODE                 VARCHAR2(8 BYTE),
  UK_PCT_RES_CODE                VARCHAR2(8 BYTE),
  INTER_FACILITY_TO_VISIT_ID     NUMBER(12),
  INTER_FACILITY_FROM_VISIT_ID   NUMBER(12),
  CID                            NUMBER(14),
  admission_year  CHAR(4 BYTE) AS (TO_CHAR(admission_date_time, 'YYYY'))
)
COMPRESS BASIC
PARTITION BY RANGE(admission_year, network)
SUBPARTITION BY HASH(visit_id) SUBPARTITIONS 16
(
  PARTITION old_data VALUES LESS THAN('2014','CBN'),
  PARTITION cbn_2014 VALUES LESS THAN('2014','GP1'),
  PARTITION gp1_2014 VALUES LESS THAN('2014','GP2'),
  PARTITION gp2_2014 VALUES LESS THAN('2014','NBN'),
  PARTITION nbn_2014 VALUES LESS THAN('2014','NBX'),
  PARTITION nbx_2014 VALUES LESS THAN('2014','QHN'),
  PARTITION qhn_2014 VALUES LESS THAN('2014','SBN'),
  PARTITION sbn_2014 VALUES LESS THAN('2014','SMN'),
  PARTITION smn_2014 VALUES LESS THAN('2015','CBN'),
  PARTITION cbn_2015 VALUES LESS THAN('2015','GP1'),
  PARTITION gp1_2015 VALUES LESS THAN('2015','GP2'),
  PARTITION gp2_2015 VALUES LESS THAN('2015','NBN'),
  PARTITION nbn_2015 VALUES LESS THAN('2015','NBX'),
  PARTITION nbx_2015 VALUES LESS THAN('2015','QHN'),
  PARTITION qhn_2015 VALUES LESS THAN('2015','SBN'),
  PARTITION sbn_2015 VALUES LESS THAN('2015','SMN'),
  PARTITION smn_2015 VALUES LESS THAN('2016','CBN'),
  PARTITION cbn_2016 VALUES LESS THAN('2016','GP1'),
  PARTITION gp1_2016 VALUES LESS THAN('2016','GP2'),
  PARTITION gp2_2016 VALUES LESS THAN('2016','NBN'),
  PARTITION nbn_2016 VALUES LESS THAN('2016','NBX'),
  PARTITION nbx_2016 VALUES LESS THAN('2016','QHN'),
  PARTITION qhn_2016 VALUES LESS THAN('2016','SBN'),
  PARTITION sbn_2016 VALUES LESS THAN('2016','SMN'),
  PARTITION smn_2016 VALUES LESS THAN('2017','CBN'),
  PARTITION cbn_2017 VALUES LESS THAN('2017','GP1'),
  PARTITION gp1_2017 VALUES LESS THAN('2017','GP2'),
  PARTITION gp2_2017 VALUES LESS THAN('2017','NBN'),
  PARTITION nbn_2017 VALUES LESS THAN('2017','NBX'),
  PARTITION nbx_2017 VALUES LESS THAN('2017','QHN'),
  PARTITION qhn_2017 VALUES LESS THAN('2017','SBN'),
  PARTITION sbn_2017 VALUES LESS THAN('2017','SMN'),
  PARTITION smn_2017 VALUES LESS THAN('2018','CBN'),
  PARTITION cbn_2018 VALUES LESS THAN('2018','GP1'),
  PARTITION gp1_2018 VALUES LESS THAN('2018','GP2'),
  PARTITION gp2_2018 VALUES LESS THAN('2018','NBN'),
  PARTITION nbn_2018 VALUES LESS THAN('2018','NBX'),
  PARTITION nbx_2018 VALUES LESS THAN('2018','QHN'),
  PARTITION qhn_2018 VALUES LESS THAN('2018','SBN'),
  PARTITION sbn_2018 VALUES LESS THAN('2018','SMN'),
  PARTITION smn_2018 VALUES LESS THAN('2019','CBN')
);

CREATE UNIQUE INDEX pk_visit ON visit(visit_id, network) PARALLEL 16;
ALTER INDEX pk_visit NOPARALLEL;

CREATE INDEX idx_visit_cid ON visit(cid, network) LOCAL PARALLEL 16;
ALTER INDEX idx_visit_cid NOPARALLEL;
 
ALTER TABLE visit ADD CONSTRAINT pk_visit PRIMARY KEY(visit_id, network) USING INDEX pk_visit;
